sudo: required
services:
  - docker

before_install:
  - docker build -t pontusm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pontusm/react-test npm test -- --coverage

after_success:
  - docker build -t pontusm/multi-fib-client ./client
  - docker build -t pontusm/multi-fib-nginx ./nginx
  - docker build -t pontusm/multi-fib-api ./api
  - docker build -t pontusm/multi-fib-worker ./worker
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to hub.docker.com
  - docker push pontusm/multi-fib-client
  - docker push pontusm/multi-fib-nginx
  - docker push pontusm/multi-fib-api
  - docker push pontusm/multi-fib-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-396622648835
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
